[package]
name = "MurlocVillage_Launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-alpha.1"
qmetaobject = "0.2.10"
qt_core = "0.5"
qt_widgets = "0.5"
cxx = "1.0.83"
cxx-qt = "0.5"
cxx-qt-lib = "0.5"
image = "0.24"

[build-dependencies]
cxx-qt-build = "0.5"