name: Rust

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Qt Dependencies
        run: sudo apt-get install qtbase5-dev libqt5widgets5 qtdeclarative5-dev qt5-qmake libqt5core5a libqt5gui5 libqt5qml5
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true
      - name: Build
        run: cargo build --verbose
      - name: Run Tests
        run: cargo test --verbose
      - name: Run Clippy
        run: cargo clippy -- -D warnings
      - name: Run Rustfmt
        run: cargo fmt -- --check
